export const constant = {
  ADMIN: "Admin",
  USER: "User",
  PUBLISH: "Publish",
  UNPUBLISH: "Unpublish",
  SIGNUP: "Sign Up",
  LOGIN: "Log in",
  EMAIL: "Email",
  PASSWORD: "Password",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  DOB: "DOB",
  ROLE: "Role",
  STATUS: "Status",
  ACTIVE: "Active",
  DEACTIVE: "Deactive",
  SUBMIT: "Submit",
  CREATE_ACCOUNT: "Create new account",
  ACTIVE_ACCOUNT: "Active account",
  CREATE_BLOG: "Create new blog",
  TITLE: "Title",
  DESCRIPTION: "Description",
  PUBLISED_DATE: "Publised Date",
  MODIFY_DATE: "Modify Date",
  CATEGORY: "Category",
  AUTHOR: "Author",
  ACTIONS: "Actions",
  BACK: "Back",
};
